#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ascii___Text.Resource", IsApplication=true)]

namespace Ascii___Text
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Tesseract.Droid.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::Tesseract.Droid.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
			global::XLabs.IOC.TinyIOC.Droid.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::XLabs.IOC.TinyIOC.Droid.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
			global::XLabs.Platform.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int bases_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int AsciiBox = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int LabelAscii = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int LabelText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TextBox = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int photoBT = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int spinner = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int tableRow1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int tableRow3 = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int tableRow4 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int base_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
