#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ascii___Text.Resource", IsApplication=true)]

namespace Ascii___Text
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Tesseract.Droid.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::Tesseract.Droid.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.Color.calendar_active_month_bg = global::Ascii___Text.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_bg = global::Ascii___Text.Resource.Color.calendar_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_divider = global::Ascii___Text.Resource.Color.calendar_divider;
			global::XLabs.Forms.Droid.Resource.Color.calendar_highlighted_day_bg = global::Ascii___Text.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_inactive_month_bg = global::Ascii___Text.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_day_bg = global::Ascii___Text.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_range_bg = global::Ascii___Text.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_active = global::Ascii___Text.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_inactive = global::Ascii___Text.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selected = global::Ascii___Text.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selector = global::Ascii___Text.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_unselectable = global::Ascii___Text.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::Ascii___Text.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::Ascii___Text.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_topmargin = global::Ascii___Text.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_medium = global::Ascii___Text.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_small = global::Ascii___Text.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Droid.Resource.Drawable.ad16 = global::Ascii___Text.Resource.Drawable.ad16;
			global::XLabs.Forms.Droid.Resource.Drawable.calendar_bg_selector = global::Ascii___Text.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Droid.Resource.Id.calendar_grid = global::Ascii___Text.Resource.Id.calendar_grid;
			global::XLabs.Forms.Droid.Resource.Id.calendar_view = global::Ascii___Text.Resource.Id.calendar_view;
			global::XLabs.Forms.Droid.Resource.Id.calendarr_pager = global::Ascii___Text.Resource.Id.calendarr_pager;
			global::XLabs.Forms.Droid.Resource.Id.left_arrow = global::Ascii___Text.Resource.Id.left_arrow;
			global::XLabs.Forms.Droid.Resource.Id.right_arrow = global::Ascii___Text.Resource.Id.right_arrow;
			global::XLabs.Forms.Droid.Resource.Id.title = global::Ascii___Text.Resource.Id.title;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager = global::Ascii___Text.Resource.Layout.calendar_pager;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager_layout = global::Ascii___Text.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_picker = global::Ascii___Text.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Droid.Resource.Layout.dialog = global::Ascii___Text.Resource.Layout.dialog;
			global::XLabs.Forms.Droid.Resource.Layout.month = global::Ascii___Text.Resource.Layout.month;
			global::XLabs.Forms.Droid.Resource.Layout.week = global::Ascii___Text.Resource.Layout.week;
			global::XLabs.Forms.Droid.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::XLabs.Forms.Droid.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.String.day_name_format = global::Ascii___Text.Resource.String.day_name_format;
			global::XLabs.Forms.Droid.Resource.String.full_date_format = global::Ascii___Text.Resource.String.full_date_format;
			global::XLabs.Forms.Droid.Resource.String.invalid_date = global::Ascii___Text.Resource.String.invalid_date;
			global::XLabs.Forms.Droid.Resource.String.library_name = global::Ascii___Text.Resource.String.library_name;
			global::XLabs.Forms.Droid.Resource.String.month_name_format = global::Ascii___Text.Resource.String.month_name_format;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell = global::Ascii___Text.Resource.Style.CalendarCell;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_CalendarDate = global::Ascii___Text.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_DayHeader = global::Ascii___Text.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Droid.Resource.Style.CalendarTitle = global::Ascii___Text.Resource.Style.CalendarTitle;
			global::XLabs.IOC.TinyIOC.Droid.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::XLabs.IOC.TinyIOC.Droid.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
			global::XLabs.Platform.Resource.String.ApplicationName = global::Ascii___Text.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::Ascii___Text.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int calendar_text_selector = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonshape = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar_bg_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int txtbox_9 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int AsciiBox = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int LabelAscii = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int LabelText = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextBox = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int calendar_grid = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int calendar_view = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int calendarr_pager = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int left_arrow = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int photoBT = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int right_arrow = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int spinner = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_pager_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int calendar_picker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int month = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int week = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int base_prompt = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
